### ISSUE TITLE
Relationship to custom post Type of subsite?

### ISSUE THREAD

**Issue by abombelli** [jonathan-dejong/acf-sites#1]
Hello

Just came across your plugin!
I was wondering if there is a way to select a site and then get a relationship field populated with costum post types from the selected site?

This would be awesome!

Cheers,
Aldo

**Comment by jonathan-dejong** [comment]
Hi Aldo, 

I see the usability for such a feature :) 
However it's way beyond the scope of what this field is trying to achieve.. 

Also, looking into the available filters for the relationship-field it doesn't seem possible to do this with the default relationship-field. Maaaaaaaybe if you looked into how it's fetching the posts via ajax and see if you can hook into that in some way but likely not. 

I first figured you could use this filter: http://www.advancedcustomfields.com/resources/actions/ac-finput-form_data/
to add a switch_to_blog() function before the field but it wont work since it'll not take into account what site you select from the subsites-dropdown. 

So sorry, currently it does not seem possible without heavy coding and modifications :) 

Tho It'd be really sweet if Elliot added the ability to select a site within the network (if a network is installed) from which to choose posts in the relationship-field. I'm likely going to need that function myself soon enough.

**Comment by abombelli** [comment]
Hi Jonathan

Thanks a lot for your quick feedback!
Would be great if Elliot could implement that. I'm searching and searching the internet for such a plugin. Strangely there is nothing where posts can be related across a  multisite network.

**Comment by jonathan-dejong** [comment]
I've previously solved such a function by using this plugin:https://premium.wpmudev.org/project/post-indexer/

Then created a true/false checkbox using ACF on the posts (like "show this post globally?").. Then I can do my own custom queries with post indexer checking for the meta value of the ACF true/false field. It'll require some digging into the code for you tho to find the necessery query functions :)

**Comment by jonathan-dejong** [comment]
So I decided to give this a try today.. 

I figured I could make use of the query filter for the relationship field. Update it using a custom ajax function which listened to my sites dropdown.. Unfortunately add_filter does not work in ajax so that was a dead end. I don't think this will be possible to do in a add-on.. It's something Elliot has to add in the core functionality and I wouldn't get my hopes up :/

**Comment by abombelli** [comment]
I sent Elliot a feature request two day ago.
Let's see ;-)
But thanks for trying!
